const $=id=>document.getElementById(id);const API_BASE=location.protocol==='file:'?'http://127.0.0.1:8080':'';let selected=null,watching=false,count=0,timer=null,jobId=null,apiOnline=false;
let trains=[['KTX 101','06:00','08:38','2시간 38분','일반실 가능','KTX'],['무궁화호 1201','06:20','11:35','5시간 15분','일반실 매진','무궁화호'],['KTX 105','07:10','09:48','2시간 38분','일반실 가능','KTX'],['ITX-새마을 1001','08:05','11:52','3시간 47분','일반실 가능','새마을호'],['KTX 111','08:40','11:18','2시간 38분','특실 가능','KTX'],['KTX 123','09:10','11:48','2시간 38분','일반실 가능','KTX'],['무궁화호 1411','09:32','14:48','5시간 16분','일반실 매진','무궁화호'],['ITX-새마을 1003','10:05','13:52','3시간 47분','일반실 가능','새마을호'],['KTX 127','10:30','13:08','2시간 38분','특실 가능','KTX'],['KTX 135','12:10','14:48','2시간 38분','일반실 가능','KTX'],['무궁화호 1421','14:20','19:36','5시간 16분','일반실 가능','무궁화호'],['KTX 151','18:30','21:08','2시간 38분','일반실 가능','KTX']];
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function activeType(){return document.querySelector('#trainTypes .chip.active')?.textContent||'전체'}
function setStatus(text,kind){$('statusBadge').textContent=text;$('statusBadge').className='badge '+kind}
function render(){const list=$('trainList');list.innerHTML='';const min=$('time').value||'00:00',type=activeType();const visible=trains.map((t,i)=>({t,i})).filter(x=>x.t[1]>=min&&(type==='전체'||x.t[5]===type));if(!visible.length){list.innerHTML='<p class="empty">조건에 맞는 열차가 없습니다.</p>';return}visible.forEach(({t,i})=>{const d=document.createElement('div');d.className='train';d.innerHTML=`<div class="train-head"><strong>${t[0]}</strong><span class="train-meta">${t[4]}</span></div><div class="train-time">${t[1]} <small>→</small> ${t[2]}</div><div class="train-meta">${t[3]} · ${$('from').value||'출발역'} → ${$('to').value||'도착역'}</div><button class="choose ${selected===i?'selected':''}" data-i="${i}">${selected===i?'선택됨':'이 열차 선택'}</button>`;list.appendChild(d)});document.querySelectorAll('.choose').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.i);$('watchBtn').disabled=false;$('korailOpenBtn').disabled=false;$('watchBtn').textContent='좌석 감시 시작';render()})}
$('korailOpenBtn').onclick=()=>window.open('https://www.korail.com/ticket/reserve/nonmember','_blank','noopener');
$('loginBtn').onclick=()=>{if(!$('korailId').value||!$('korailPw').value){alert('아이디와 비밀번호를 입력하세요.');return}$('loginCard').classList.add('hidden');$('mainView').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('date').value=localDate()};
$('logoutBtn').onclick=()=>{stop();$('mainView').classList.add('hidden');$('loginCard').classList.remove('hidden');$('logoutBtn').classList.add('hidden');$('korailPw').value='';selected=null};
$('searchBtn').onclick=async()=>{if(!$('from').value||!$('to').value||!$('date').value){alert('출발역, 도착역, 출발일을 입력하세요.');return}selected=null;$('watchBtn').disabled=true;$('korailOpenBtn').disabled=true;$('results').classList.remove('hidden');setStatus('조회 중','running');$('lastAction').textContent='코레일 공식 페이지에서 열차를 조회하고 있습니다.';try{const res=await fetch(API_BASE+'/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({departure_station:$('from').value,arrival_station:$('to').value,departure_date:$('date').value,departure_time:$('time').value})});if(!res.ok)throw new Error('search');const data=await res.json();trains=data.trains.map((x,i)=>[x.raw, '', '', '', '코레일 결과', '전체']);render();setStatus('대기 중','idle');$('lastAction').textContent=`코레일에서 ${trains.length}개 결과를 불러왔습니다.`}catch(e){setStatus('오류','error');$('lastAction').textContent='코레일 검색에 실패했습니다. 서버 로그를 확인하세요.';alert('코레일 검색에 실패했습니다.')}};
$('watchBtn').onclick=async()=>{if(watching){await stop();return}if(selected===null)return;const payload={departure_station:$('from').value,arrival_station:$('to').value,departure_date:$('date').value,interval_seconds:Number($('interval').value),any_seat:$('anySeat').checked};try{const res=await fetch(API_BASE+'/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error('작업 등록 실패');const job=await res.json();jobId=job.id;apiOnline=true}catch(e){apiOnline=false;setStatus('서버 연결 오류','error');$('lastAction').textContent='서버에 연결할 수 없습니다. 서버 실행 상태를 확인하세요.';return}watching=true;count=0;$('watchBtn').textContent='좌석 감시 중지';setStatus('실행 중','running');$('lastAction').textContent=`${trains[selected][0]}의 가능한 좌석을 감시 중입니다.`;tick()};
$('testNotifyBtn').onclick=async()=>{const tg=$('telegramTarget').value.trim(),mail=$('emailTarget').value.trim();if(!tg&&!mail){alert('텔레그램 Chat ID 또는 이메일 주소를 입력하세요.');return}try{const res=await fetch(API_BASE+'/api/notify/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({telegram_target:tg,email_target:mail,message:'열차 감시 테스트 알림입니다.'})});const result=await res.json();if(!res.ok)throw new Error('전송 실패');alert(result.sent.length?'알림을 전송했습니다: '+result.sent.join(', '):'서버는 응답했지만 연결된 알림 채널이 없습니다.');$('lastAction').textContent='알림 테스트를 완료했습니다.'}catch(e){alert('알림 서버에 연결할 수 없습니다.');$('lastAction').textContent='알림 테스트 실패'} };
async function tick(){if(!watching)return;try{const res=await fetch(API_BASE+'/api/jobs/'+jobId,{cache:'no-store'});if(!res.ok)throw new Error('job');const job=await res.json();apiOnline=true;count=job.check_count;$('lastChecked').textContent=job.last_checked_at?new Date(job.last_checked_at).toLocaleTimeString('ko-KR'):'대기 중';$('checkCount').textContent=count+'회'}catch(e){apiOnline=false;setStatus('서버 연결 오류','error');$('lastAction').textContent='서버 연결이 끊겼습니다.';return}const now=new Date(),next=new Date(now.getTime()+Number($('interval').value)*1000);$('nextChecked').textContent=next.toLocaleTimeString('ko-KR');timer=setTimeout(tick,Number($('interval').value)*1000)}
async function stop(){watching=false;if(timer)clearTimeout(timer);if(jobId){try{await fetch(API_BASE+'/api/jobs/'+jobId,{method:'DELETE'})}catch(e){}jobId=null}if($('watchBtn'))$('watchBtn').textContent=selected===null?'열차를 선택하세요':'좌석 감시 시작';if($('statusBadge'))setStatus('대기 중','idle')}
document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active')});
document.addEventListener('visibilitychange',()=>{if(watching&&document.hidden){$('lastAction').textContent='백그라운드 상태입니다. 서버 감시는 계속 시도됩니다.'}else if(watching){$('lastAction').textContent=`${trains[selected][0]}의 가능한 좌석을 감시 중입니다.`}});
