const $ = id => document.getElementById(id);
const API_BASE = location.protocol === 'file:' ? 'http://127.0.0.1:8080' : '';
let trains = [], selected = null, jobId = null, watching = false, timer = null;
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function setStatus(t,k){$('statusBadge').textContent=t;$('statusBadge').className='badge '+k}
function render(){const list=$('trainList');list.innerHTML='';if(!trains.length){list.innerHTML='<p class="empty">코레일 검색 결과가 없습니다.</p>';return}trains.forEach((x,i)=>{const row=document.createElement('div');row.className='train';row.innerHTML=`<div class="train-head"><strong>코레일 검색 결과 ${i+1}</strong></div><div class="live-text">${x.raw}</div><button class="choose ${selected===i?'selected':''}" data-i="${i}">${selected===i?'선택됨':'이 열차 선택'}</button>`;list.appendChild(row)});document.querySelectorAll('.choose').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.i);$('watchBtn').disabled=false;$('korailOpenBtn').disabled=false;render()})}
$('loginBtn').onclick=()=>{if(!$('korailId').value||!$('korailPw').value)return alert('아이디와 비밀번호를 입력하세요.');$('loginCard').classList.add('hidden');$('mainView').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('date').value=localDate()};
$('logoutBtn').onclick=async()=>{await stop();$('mainView').classList.add('hidden');$('loginCard').classList.remove('hidden');$('logoutBtn').classList.add('hidden');$('korailPw').value=''};
$('searchBtn').onclick=async()=>{if(!$('from').value||!$('to').value||!$('date').value)return alert('출발역, 도착역, 출발일을 입력하세요.');selected=null;trains=[];render();$('watchBtn').disabled=true;$('korailOpenBtn').disabled=true;setStatus('조회 중','running');$('lastAction').textContent='코레일 페이지를 여는 중입니다. 최대 60초 걸릴 수 있습니다.';try{const r=await fetch(`${API_BASE}/api/search`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({departure_station:$('from').value,arrival_station:$('to').value,departure_date:$('date').value,departure_time:$('time').value})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'검색 실패');trains=d.trains||[];render();setStatus('대기 중','idle');$('lastAction').textContent=`코레일 실제 검색 결과 ${trains.length}건`}catch(e){setStatus('오류','error');$('lastAction').textContent=`코레일 검색 실패: ${e.message}`;alert(`코레일 검색 실패: ${e.message}`)}};
$('watchBtn').onclick=async()=>{if(watching)return stop();if(selected===null)return;try{const r=await fetch(`${API_BASE}/api/jobs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({departure_station:$('from').value,arrival_station:$('to').value,departure_date:$('date').value,interval_seconds:Number($('interval').value),any_seat:$('anySeat').checked})});if(!r.ok)throw new Error('감시 작업 등록 실패');jobId=(await r.json()).id;watching=true;$('watchBtn').textContent='좌석 감시 중지';setStatus('실행 중','running');pollJob()}catch(e){setStatus('오류','error');$('lastAction').textContent=e.message}};
async function pollJob(){if(!watching)return;try{const r=await fetch(`${API_BASE}/api/jobs/${jobId}`,{cache:'no-store'});if(!r.ok)throw new Error('감시 작업 연결 실패');const j=await r.json();$('lastChecked').textContent=j.last_checked_at?new Date(j.last_checked_at).toLocaleTimeString('ko-KR'):'대기 중';$('checkCount').textContent=`${j.check_count}회`}catch(e){setStatus('오류','error');$('lastAction').textContent=e.message}timer=setTimeout(pollJob,Number($('interval').value)*1000)}
async function stop(){watching=false;if(timer)clearTimeout(timer);if(jobId){try{await fetch(`${API_BASE}/api/jobs/${jobId}`,{method:'DELETE'})}catch(e){}jobId=null}if($('watchBtn'))$('watchBtn').textContent=selected===null?'열차를 선택하세요':'좌석 감시 시작';if($('statusBadge'))setStatus('대기 중','idle')}
$('testNotifyBtn').onclick=async()=>{const tg=$('telegramTarget').value.trim(),mail=$('emailTarget').value.trim();if(!tg&&!mail)return alert('텔레그램 Chat ID 또는 이메일 주소를 입력하세요.');try{const r=await fetch(`${API_BASE}/api/notify/test`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({telegram_target:tg,email_target:mail,message:'열차 감시 테스트 알림입니다.'})});const d=await r.json();if(!r.ok)throw new Error(d.errors?.join(', ')||'전송 실패');alert(d.sent.length?`전송 완료: ${d.sent.join(', ')}`:'연결된 알림 채널이 없습니다.')}catch(e){alert(`알림 실패: ${e.message}`)}};
$('korailOpenBtn').onclick=()=>window.open('https://www.korail.com/ticket/search/general','_blank','noopener');
document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active')});
